name: SLSA Source Attestation
on:
  push:

# Declare default permissions as read only.
permissions: read-all

jobs:
  sbom:
    name: SLSA
    runs-on: ubuntu-latest
    permissions:
      # Used to receive a badge. (Upcoming feature)
      id-token: write
      contents: write
    
    steps:
      - name: "Checkout code"
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: "Generate provenance"
        run: |
          gh pr list --search $(git rev-parse HEAD) --state=all --json "number,url,reviewDecision,reviews" > review.json
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: "install gitsign"
        run: |
          go install github.com/sigstore/gitsign/cmd/gitsign-attest@94337a4572db6a2b3a593ba04dd5ad23ae72c498
      - name: "Attest"
        run: |
          set -e
          git config --global user.email "gitsign-attest@noreply.github.com"
          git config --global user.name "Attest"
          
          git fetch origin refs/attestations/commits:refs/attestations/commits || true
          gitsign-attest -f review.json --type custom

          git push origin refs/attestations/commits