name: Scorecards
on:
  push:

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      actions: read
      contents: write
    
    steps:
      - name: "Checkout code"
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - name: "Run analysis"
        uses: ossf/scorecard-action@main
        with:
          results_file: scorecard.json
          results_format: json
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          cache: true
      - name: "install gitsign"
        run: |
          go install github.com/sigstore/gitsign/cmd/gitsign-attest@33544a49e8b05038daa75f60485c115cc3902e69
      - name: "Attest"
        run: |
          set -e
          git config --global user.email "gitsign-attest@noreply.github.com"
          git config --global user.name "Attest"
          
          git fetch origin refs/attestations/commits:refs/attestations/commits || true
          gitsign-attest -f scorecard.json --type custom

          git push origin refs/attestations/commits